language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - composer selfupdate
  - composer install --no-interaction --prefer-source

after_script:
  - vendor/bin/test-reporter

notifications:
  email: "demateus@gmail.com"